apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>3HTP lab</title>
    </head>

    <body>
    Hello World
    </body>

    </html>
kind: ConfigMap
metadata:
  name: lab-configmap
  namespace: default
